# Generated by Django 2.2 on 2021-11-09 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequests',
            fields=[
                ('req_id', models.AutoField(db_column='Req_id', primary_key=True, serialize=False)),
                ('leave_sdate', models.DateField(db_column='Leave_SDate')),
                ('leave_edate', models.DateField(db_column='Leave_EDate')),
                ('leave_type', models.CharField(db_column='Leave_Type', max_length=700)),
                ('applications', models.CharField(blank=True, db_column='Applications', max_length=700, null=True)),
                ('statuses', models.IntegerField(db_column='Statuses')),
                ('date_of_application', models.DateField(blank=True, db_column='Date_of_application', null=True)),
                ('dep', models.ForeignKey(db_column='Dep_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Dept')),
                ('emp', models.ForeignKey(db_column='Emp_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Employees')),
            ],
            options={
                'db_table': 'leave_requests',
            },
        ),
    ]
