# Generated by Django 3.2.7 on 2021-11-08 10:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('today_date', models.DateField(db_column='Date', default=datetime.datetime.now)),
                ('entry_time', models.TimeField(db_column='Entry Time')),
                ('exit_time', models.TimeField(db_column='Exit Time')),
                ('working_hrs', models.CharField(db_column='Working hours', default='00:00', max_length=100)),
                ('att_id', models.AutoField(db_column='Attendence_id', primary_key=True, serialize=False)),
                ('deptid', models.ForeignKey(db_column='department ID', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.dept')),
                ('emaill', models.ForeignKey(db_column='email id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('emp', models.ForeignKey(db_column='Emp ID', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.employees')),
            ],
            options={
                'db_table': 'attendence',
            },
        ),
    ]
