# Generated by Django 3.2.7 on 2021-10-20 18:01

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_hod', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
                ('eemail', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('desg_id', models.BigIntegerField(db_column='Desg_id', primary_key=True, serialize=False)),
                ('desgname', models.CharField(db_column='DesgName', max_length=100)),
            ],
            options={
                'db_table': 'designation',
            },
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('dep_id', models.BigIntegerField(db_column='Dep_id')),
                ('firstname', models.CharField(db_column='FirstName', max_length=100)),
                ('lastname', models.CharField(db_column='LastName', max_length=100)),
                ('deptname', models.CharField(db_column='DeptName', max_length=100)),
                ('gender', models.CharField(db_column='Gender', max_length=100)),
            ],
            options={
                'db_table': 'dept',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('emp_id', models.BigIntegerField(db_column='Emp_id')),
                ('firstname', models.CharField(db_column='FirstName', max_length=100)),
                ('lastname', models.CharField(db_column='LastName', max_length=100)),
                ('gender', models.CharField(db_column='Gender', max_length=100)),
                ('passwords', models.CharField(db_column='Passwords', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('dob', models.DateField(db_column='DOB')),
                ('contact', models.IntegerField(db_column='Contact')),
                ('addresses', models.CharField(db_column='Addresses', max_length=700)),
                ('images', models.CharField(blank=True, db_column='Images', max_length=100, null=True)),
                ('hire_date', models.DateField(db_column='Hire_date')),
                ('metrocity', models.IntegerField(db_column='Metrocity')),
                ('no_of_children', models.IntegerField(db_column='No_of_Children')),
                ('dep', models.ForeignKey(db_column='Dep_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.dept')),
                ('desg', models.ForeignKey(db_column='Desg_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.designation')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequests',
            fields=[
                ('req_id', models.BigIntegerField(db_column='Req_id', primary_key=True, serialize=False)),
                ('leave_date', models.DateField(db_column='Leave_Date')),
                ('leave_type', models.CharField(db_column='Leave_Type', max_length=700)),
                ('applications', models.CharField(blank=True, db_column='Applications', max_length=700, null=True)),
                ('statuses', models.IntegerField(db_column='Statuses')),
                ('lop', models.IntegerField(db_column='LOP')),
                ('date_of_application', models.DateField(blank=True, db_column='Date_of_application', null=True)),
                ('dep', models.ForeignKey(db_column='Dep_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.dept')),
                ('emp', models.ForeignKey(db_column='Emp_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.employees')),
            ],
            options={
                'db_table': 'leave_requests',
            },
        ),
        migrations.AddField(
            model_name='designation',
            name='dep',
            field=models.ForeignKey(db_column='Dep_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.dept'),
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('ded_id', models.BigIntegerField(db_column='Ded_id', primary_key=True, serialize=False)),
                ('lop_days', models.IntegerField(blank=True, db_column='LOP_days', null=True)),
                ('pf', models.FloatField(db_column='PF')),
                ('esic', models.FloatField(db_column='ESIC')),
                ('tax', models.FloatField(db_column='TAX')),
                ('lwf', models.FloatField(blank=True, db_column='LWF', null=True)),
                ('nps', models.FloatField(blank=True, db_column='NPS', null=True)),
                ('lop', models.FloatField(blank=True, db_column='LOP', null=True)),
                ('emp', models.ForeignKey(db_column='Emp_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.employees')),
            ],
            options={
                'db_table': 'deductions',
            },
        ),
        migrations.CreateModel(
            name='ComplementarySalary',
            fields=[
                ('comp_id', models.BigIntegerField(db_column='Comp_id', primary_key=True, serialize=False)),
                ('bonus', models.FloatField(blank=True, db_column='BONUS', null=True)),
                ('ma', models.FloatField(blank=True, db_column='MA', null=True)),
                ('hra', models.FloatField(blank=True, db_column='HRA', null=True)),
                ('per_inc', models.IntegerField(blank=True, db_column='per_INC', null=True)),
                ('cea', models.FloatField(blank=True, db_column='CEA', null=True)),
                ('emp', models.ForeignKey(db_column='Emp_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.employees')),
            ],
            options={
                'db_table': 'complementary_salary',
            },
        ),
        migrations.CreateModel(
            name='BaseSalary',
            fields=[
                ('salary_id', models.BigIntegerField(db_column='Salary_id', primary_key=True, serialize=False)),
                ('amount', models.FloatField(db_column='Amount')),
                ('da', models.FloatField(blank=True, db_column='DA', null=True)),
                ('desg', models.ForeignKey(db_column='Desg_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.designation')),
                ('dep', models.ForeignKey(db_column='Dep_id', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.dept')),
            ],
            options={
                'db_table': 'base_salary',
            },
        ),
    ]
