# Generated by Django 2.2 on 2021-11-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysalary',
            name='lwf',
        ),
    ]
