# Generated by Django 3.2.7 on 2021-10-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211020_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='dept',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='passwords',
        ),
    ]
