# Generated by Django 3.2.7 on 2021-10-20 19:40

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211021_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complementarysalary',
            name='emp',
        ),
        migrations.AddField(
            model_name='complementarysalary',
            name='training_year',
            field=models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), accounts.models.max_value_current_year]),
        ),
    ]
