# Generated by Django 3.2.7 on 2021-10-20 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211021_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complementarysalary',
            old_name='training_year',
            new_name='year',
        ),
    ]
